In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import linear_model

In [2]:
df=pd.read_csv("homeprices.csv")
print(df)

   area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000


In [3]:
reg=linear_model.LinearRegression()
reg.fit(df[['area']],df.price) 

LinearRegression()

In [4]:
reg.predict([[3300]])

array([628715.75342466])

### Saving this model So that i can use anytime

In [5]:
import pickle

In [7]:
with open('TrainedsimlelinearRegressionModel','wb') as a:
    pickle.dump(reg,a)  # reg=jyta save korte chai
    

#### TrainedsimlelinearRegressionModel file created into directory

#### Lets opennit now

In [8]:
with open('TrainedsimlelinearRegressionModel','rb') as a:
    lr=pickle.load(a)   
    
#lr object/variable r modhye file ta raklm lr object use kore ai bar kaj(prediction) ta korte parbo 

In [9]:
lr.predict([[3300]])

array([628715.75342466])

#### So now i can send this file to someone and he can use (to predict)

#### Another way

In [14]:
import pickle
filename = 'Trained_model_SimlelinearRegression.sav'
pickle.dump(reg, open(filename, 'wb'))

In [15]:
lr1 = pickle.load(open('Trained_model_SimlelinearRegression.sav','rb'))

In [16]:
lr1.predict([[3300]])

array([628715.75342466])

#### =========  joblib========

### if we have more no of numpy array then joblib more efficient way to do

In [17]:
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\HP\anaconda3\lib\site-packages\sklearn\externals\__init__.py)